# Generated by Django 3.0.2 on 2020-03-31 19:07

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleManufacturers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2010, validators=[django.core.validators.MaxValueValidator(2020), django.core.validators.MinValueValidator(1970)])),
                ('litre', models.DecimalField(decimal_places=1, max_digits=2)),
                ('vehicle_type', models.CharField(choices=[('C', 'Car'), ('M', 'Mini-Van'), ('B', 'Bike')], max_length=1)),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual'), ('S', 'Semi-automatic')], max_length=1)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.VehicleManufacturers')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOwnership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Stock keep unit of max 50 character <a href="https://www.isbn-international.org/content/what-isbn">SKU</a>', max_length=50)),
                ('vin', models.CharField(max_length=17)),
                ('colour', models.CharField(max_length=10)),
                ('damage_category', models.CharField(choices=[('C', 'C: Can be repaired, but it would cost more than the vehicle’s worth.'), ('N', 'N: Can be repaired following non-structural damage. This replaced category C in October 2017.'), ('B', 'B: Can’t be repaired. The body shell has to be crushed, but you can salvage other parts from it.'), ('A', 'A: Can’t be repaired. The entire vehicle has to be crushed.'), ('S', 'S: Can be repaired following structural damage. This replaced category D in October 2017.'), ('D', 'D: Can be repaired and would cost less than the vehicle’s worth, but other costs such as transporting your vehicle take it over the vehicle’s value.')], max_length=1)),
                ('damage_primary', models.CharField(default='None', max_length=50)),
                ('damage_secondary', models.CharField(default='None', max_length=50)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2020, 3, 31, 20, 7, 25, 57540))),
                ('cost_price', models.IntegerField(validators=[django.core.validators.MaxValueValidator(999999), django.core.validators.MinValueValidator(99)])),
                ('slug', models.SlugField(max_length=100)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.Location')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.VehicleModel')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.VehicleOwnership')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.VehicleOwnership')),
            ],
        ),
    ]
