# Generated by Django 3.0.2 on 2020-04-01 18:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20200401_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.PROTECT, to='inventory.PartCategory'),
        ),
        migrations.AlterField(
            model_name='vehicleownership',
            name='damage_category',
            field=models.CharField(choices=[('B', 'B: Can’t be repaired. The body shell has to be crushed, but you can salvage other parts from it.'), ('S', 'S: Can be repaired following structural damage. This replaced category D in October 2017.'), ('C', 'C: Can be repaired, but it would cost more than the vehicle’s worth.'), ('D', 'D: Can be repaired and would cost less than the vehicle’s worth, but other costs such as transporting your vehicle take it over the vehicle’s value.'), ('A', 'A: Can’t be repaired. The entire vehicle has to be crushed.'), ('N', 'N: Can be repaired following non-structural damage. This replaced category C in October 2017.')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicleownership',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 1, 19, 28, 22, 309909)),
        ),
    ]
