# Generated by Django 3.0.2 on 2020-05-07 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0073_auto_20200503_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='condition',
            field=models.CharField(choices=[('U', 'Used'), ('R', 'Remanufactured'), ('O', 'Other')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='vehicleownership',
            name='damage_category',
            field=models.CharField(choices=[('C', 'C: Can be repaired, but it would cost more than the vehicle’s worth.'), ('D', 'D: Can be repaired and would cost less than the vehicle’s worth, but other costs such as transporting your vehicle take it over the vehicle’s value.'), ('N', 'N: Can be repaired following non-structural damage. This replaced category C in October 2017.'), ('A', 'A: Can’t be repaired. The entire vehicle has to be crushed.'), ('S', 'S: Can be repaired following structural damage. This replaced category D in October 2017.'), ('B', 'B: Can’t be repaired. The body shell has to be crushed, but you can salvage other parts from it.')], max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicleownership',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 12, 16, 0, 98482)),
        ),
    ]
