from inventory.views.vehicles.vehicle import *
from inventory.views.vehicles.models import *
from inventory.views.parts.part import *
from inventory.views.settings.setting import *
from inventory.views.settings.part import *
from inventory.views.settings.manufacturer import *
from inventory.views.settings.location import *
from inventory.views.import_export.export_views import *
from inventory.views.import_export.import_views import *
from inventory.views.settings.company import *