# Generated by Django 3.0.2 on 2020-04-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('sir', 'Sir'), ('mam', "Ma'am"), ('mad', 'Madam'), ('mr', 'Mr'), ('mrs', 'Mrs'), ('ms', 'Ms'), ('mis', 'Miss'), ('dr', 'Dr'), ('pro', 'Professor')], max_length=3)),
                ('surname', models.CharField(max_length=20)),
                ('other_names', models.CharField(max_length=40)),
                ('address_line', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
