# Generated by Django 3.0.2 on 2020-04-07 17:26

import datetime
from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20200407_1826'),
        ('invoice', '0002_auto_20200406_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.query.prefetch_related_objects, to='inventory.Part'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 18, 26, 2, 667752)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 7, 18, 26, 2, 667752)),
        ),
    ]
