# Generated by Django 3.0.2 on 2020-04-10 17:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20200410_1801'),
        ('invoice', '0003_auto_20200407_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='part',
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_1', to='inventory.Part'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_2', to='inventory.Part'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_3', to='inventory.Part'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_4', to='inventory.Part'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='part_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_5', to='inventory.Part'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 18, 1, 11, 696621)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 10, 18, 1, 11, 696621)),
        ),
    ]
