# Generated by Django 3.0.2 on 2020-04-16 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20200416_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line',
            field=models.CharField(default='Unspecified', max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 16, 48, 15, 832052)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post_code',
            field=models.CharField(default='Unspecified', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 16, 48, 15, 832052)),
        ),
    ]
