# Generated by Django 3.0.2 on 2020-04-16 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_auto_20200416_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reference',
            field=models.CharField(default='Unspecified', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(default='Null', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 17, 21, 8, 256728)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 17, 21, 8, 256728)),
        ),
    ]
