# Generated by Django 3.0.2 on 2020-04-16 18:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_auto_20200416_1920'),
        ('invoice', '0027_auto_20200416_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 19, 20, 9, 449288)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 19, 20, 9, 449288)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='part_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_1', to='inventory.Part'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='part_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_2', to='inventory.Part'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='part_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_3', to='inventory.Part'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='part_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_4', to='inventory.Part'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='part_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_5', to='inventory.Part'),
        ),
    ]
