# Generated by Django 3.0.2 on 2020-04-16 22:20

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0031_auto_20200416_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 23, 20, 8, 472490)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 23, 20, 8, 472490)),
        ),
    ]
