# Generated by Django 3.0.2 on 2020-04-16 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0033_auto_20200416_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='part_1',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='part_2',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='part_3',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='part_4',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='part_5',
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 23, 49, 22, 561149)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 16, 23, 49, 22, 561149)),
        ),
    ]
