# Generated by Django 3.0.2 on 2020-04-19 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0035_auto_20200418_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='images/company/')),
                ('name', models.CharField(max_length=30)),
                ('address_line1', models.CharField(max_length=30)),
                ('address_line2', models.CharField(blank=True, max_length=30, null=True)),
                ('post_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('guarantee_policy', models.TextField()),
                ('extra_info', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 1, 9, 58, 38598)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 1, 9, 58, 38598)),
        ),
    ]
