# Generated by Django 3.0.2 on 2020-04-19 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0036_auto_20200419_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/company/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 2, 11, 18, 573337)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 19, 2, 11, 18, 573337)),
        ),
    ]
