# Generated by Django 3.0.2 on 2020-04-20 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0045_auto_20200420_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 49, 30, 344905)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_type',
            field=models.CharField(choices=[('DE', 'Debit Card'), ('CA', 'Cash'), ('CC', 'Credit Card'), ('CH', 'Cheque'), ('BA', 'Bank Transfer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 22, 49, 30, 344905)),
        ),
    ]
