# Generated by Django 3.0.2 on 2020-04-20 22:03

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0046_auto_20200420_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='total_cost_inc_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 23, 3, 47, 265066)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 23, 3, 47, 265066)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sale_tax_percent',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Tax Percentage'),
        ),
    ]
