# Generated by Django 3.0.2 on 2020-04-20 22:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0048_auto_20200420_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='card_number',
            field=models.CharField(blank=True, help_text='last 4 digits', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 23, 24, 41, 892945)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 20, 23, 24, 41, 892945)),
        ),
    ]
