# Generated by Django 3.0.2 on 2020-05-01 18:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0061_auto_20200501_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 19, 39, 26, 224680)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.OneToOneField(default='None', on_delete=models.SET('None'), to='invoice.Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 19, 39, 26, 224680)),
        ),
    ]
