# Generated by Django 3.0.2 on 2020-05-03 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0062_auto_20200501_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 11, 10, 29, 165420)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 11, 10, 29, 165420)),
        ),
    ]
