# Generated by Django 3.0.2 on 2020-05-07 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0066_auto_20200503_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 12, 16, 0, 115800)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='payment_type',
            field=models.CharField(choices=[('DC', 'Debit Card'), ('CC', 'Credit Card'), ('CA', 'Cash'), ('CH', 'Cheque'), ('BA', 'Bank Transfer')], max_length=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 7, 12, 16, 0, 115800)),
        ),
    ]
