# Generated by Django 3.0.2 on 2020-05-11 02:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0069_auto_20200507_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 3, 57, 20, 671807)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.OneToOneField(default='None', on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 3, 57, 20, 671807)),
        ),
    ]
