# Generated by Django 3.0.2 on 2020-05-11 03:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0070_auto_20200511_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 4, 0, 53, 236813)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='invoice.Customer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 4, 0, 53, 236813)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reference',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
    ]
