# Generated by Django 3.0.2 on 2020-05-11 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0071_auto_20200511_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='telephone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 0, 24, 46, 642276)),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 0, 24, 46, 642276)),
        ),
    ]
