# Generated by Django 3.0.2 on 2020-04-04 02:07

from django.db import migrations, models
import ebay_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('expires', models.DateTimeField()),
                ('token', models.TextField()),
                ('production', models.BooleanField(default=False)),
                ('site_id', models.IntegerField(choices=[(0, 'United States'), (2, 'Canada'), (3, 'United Kingdom'), (15, 'Australia'), (16, 'Austria'), (23, 'Belgium (French)'), (71, 'France'), (77, 'Germany'), (100, 'eBay Motors'), (101, 'Italy'), (123, 'Belgium (Dutch)'), (146, 'Netherlands'), (186, 'Spain'), (193, 'Switzerland'), (196, 'Taiwan'), (201, 'Hong Kong'), (203, 'India'), (205, 'Ireland'), (207, 'Malaysia'), (210, 'Canada'), (211, 'Philippines'), (212, 'Poland'), (216, 'Singapore'), (218, 'Sweden'), (223, 'China')])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=40)),
                ('uuid', models.CharField(default=ebay_api.models.gen_uuid_hex, max_length=32, unique=True)),
                ('production', models.BooleanField(default=False)),
                ('site_id', models.IntegerField(choices=[(0, 'United States'), (2, 'Canada'), (3, 'United Kingdom'), (15, 'Australia'), (16, 'Austria'), (23, 'Belgium (French)'), (71, 'France'), (77, 'Germany'), (100, 'eBay Motors'), (101, 'Italy'), (123, 'Belgium (Dutch)'), (146, 'Netherlands'), (186, 'Spain'), (193, 'Switzerland'), (196, 'Taiwan'), (201, 'Hong Kong'), (203, 'India'), (205, 'Ireland'), (207, 'Malaysia'), (210, 'Canada'), (211, 'Philippines'), (212, 'Poland'), (216, 'Singapore'), (218, 'Sweden'), (223, 'China')])),
            ],
        ),
    ]
